[package]
name = "v3-voyage"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.3", features = ["full"] }
rust_decimal = "1.35.0"
rust_decimal_macros = "1.34.2"
tokio = { version = "1.38.0", features = ["full"] }
