[package]
name = "amm-voyage"
author = "Khaidar Kairbek"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.3", features = ["full"] }
tokio = { version = "1.38.0", features = ["full"] }
