[package]
name = "amm-voyage"
author = "Khaidar Kairbek"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.3", features = ["full"] }
eyre = "0.6.12"
polars = "0.41.3"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3"